[[main]]
  name = "关于"
  url="/about/me"
  weight = 1
[[main]]
  name = "博客"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "GitHub"
  url = "https://github.com/jpanther/congo"
  weight = 30
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"

[[footer]]
  name = "隐私"
  pageRef = "privacy"